export default {
  dialogPagamento:false,
  statusLogado:false,
  categorias:null,
  user:null,
  stores:null,

 fotoPrincipal:[],
 fotoCapa:[],
 fotosNegocio:[],

 //CONSTANTES
 CATEGORIAS:[
   {id:1 , nome:'Alianças', imagem:'alianca.jpg'},
   {id:2 , nome:'Aluguel Brinquedos', imagem:'Aluguel_brinquedos.jpg'},
   {id:3 , nome:'Aluguel Carros',imagem:'Aluguel_carros.jpg'},
   {id:4 , nome:'Animação',imagem:'Animacao.jpg'},
   {id:5 , nome:'Área de Lazer',imagem:'area_lazer.jpg'},
   {id:6 , nome:'Assessoria',imagem:'assessoria.jpg'},
   {id:7 , nome:'Aula de dança',imagem:'aula_danca.jpg'},
   {id:8 , nome:'Bandas',imagem:'bandas.jpg'},
   {id:9 , nome:'Barbearia',imagem:'barbearia.jpg'},
   {id:10 , nome:'Bebidas',imagem:'bebidas.jpg'},
   {id:11 , nome:'Bolos',imagem:'bolo.jpg'},
   {id:12 , nome:'Buffet Infantil',imagem:'buffet_infantil.jpg'},
   {id:13 , nome:'Buffet',imagem:'buffet.jpg'},
   {id:14 , nome:'Cabelo',imagem:'cabelo.jpg'},
   {id:15 , nome:'Cabine',imagem:'cabine.jpg'},
   {id:16 , nome:'Carvão',imagem:'carvao.jpg'},
   {id:17 , nome:'Chácara',imagem:'chacara.jpg'},
   {id:18 , nome:'Churrascaria',imagem:'churrascaria.jpg'},
   {id:19 , nome:'Churrasqueiro',imagem:'churrasqueiro.jpg'},
   {id:20 , nome:'Convites',imagem:'convites.jpg'},
   {id:21, nome:'Decoração Infantil',imagem:'decoracao_infantil.jpg'},
   {id:22, nome:'Decoração',imagem:'decoracao.jpg'},
   {id:23, nome:'Dia de noiva',imagem:'dia_noiva.jpg'},
   {id:24, nome:'Dj',imagem:'dj.jpg'},
   {id:25, nome:'Enxoval',imagem:'enxoval.jpg'},
   {id:26, nome:'Flores',imagem:'flores.jpg'},
   {id:27, nome:'Fotos',imagem:'foto.jpg'},
   {id:28, nome:'Garçom',imagem:'garcom.jpg'},
   {id:29, nome:'Gelo',imagem:'gelo.jpg'},
   {id:30, nome:'Hotel / Pousada',imagem:'hotel_pousada.jpg'},
   {id:31, nome:'Lembrancinhas',imagem:'lembrancinha.jpg'},
   {id:32, nome:'Lingerie',imagem:'lingerie.jpg'},
   {id:33, nome:'Locação móveis',imagem:'locacao_moveis.jpg'},
   {id:34, nome:'Lua de mel',imagem:'lua_mel.jpg'},
   {id:35, nome:'Mesas & Cadeiras',imagem:'mesa_cadeira.jpg'},
   {id:36, nome:'Roupa feminina',imagem:'roupa_feminina.jpg'},
   {id:37, nome:'Salão de Festa',imagem:'salao_festa.jpg'},
   {id:38, nome:'Salão Infantil',imagem:'salao_infantil.jpg'},
   {id:39, nome:'Salgados',imagem:'salgados.jpg'},
   {id:40, nome:'Sapatos',imagem:'sapatos.jpg'},
   {id:41, nome:'Segurança',imagem:'segurança.jpg'},
   {id:42, nome:'Som',imagem:'som.jpg'},
   {id:43, nome:'Temporada',imagem:'temporada.jpg'},
   {id:44, nome:'Tenda',imagem:'tenda.jpg'},
   {id:45, nome:'Toalha',imagem:'toalha.jpg'},
   {id:46, nome:'Topo Bolo',imagem:'topo_bolo.jpg'},
   {id:47, nome:'Traje', imagem:'traje.jpg'},
   {id:48, nome:'Vestido',imagem:'vestido.jpg'},
 ]
}
